Repository discordplace/discord.place, pull requests merged in 2024-08, with the labels that each got.

#43 Internationalization (WIP)
  client/.eslintrc.js
  client/app/components/Footer/AppearanceSettings/index.jsx
  client/app/components/Footer/index.jsx
  client/app/components/FullPageLoading/index.jsx
  client/app/components/Providers/Auth/index.jsx
  client/app/layout-content.js
  client/app/layout.js
  client/app/page.js
  client/lib/homePageMockData.js
  client/locales/en.json
  client/package.json
  client/pnpm-lock.yaml
  client/public/theme-preview-dark-mode.png
  client/public/theme-preview-light-mode.png
  client/stores/general/index.js
  client/stores/language/index.js
Labels: Frontend: Feature, Frontend: UI/UX

#47 Yazım hataları düzeltildi
  client/locales/tr.json
Labels: Internalization

#46 Support for Azerbaijani language
  client/config.js
  client/locales/az.json
  client/locales/translators.json
Labels: Internalization

#48 Added translation files validation workflow
  .github/scripts/.gitignore
  .github/scripts/package.json
  .github/scripts/pnpm-lock.yaml
  .github/scripts/validate-locale-files.js
  .github/workflows/validate-locale-files.yml
  README.md
Labels: Internalization

#52 Server listing requirements
  client/app/(account)/account/components/Content/Tabs/MyServers/NewServer/index.jsx
  client/locales/az.json
  client/locales/en.json
  client/locales/tr.json
  client/stores/language/index.js
  server/config.yml
  server/src/routes/auth/@me/data.js
  server/src/routes/servers/[id]/index.js
  server/src/utils/servers/requirementChecks.js
Labels: Frontend: Feature, Frontend: UI/UX, Backend: Feature, Internalization

#53 Fix badges localization
  client/app/(profiles)/profile/[slug]/content.js
  client/app/(profiles)/profile/u/[user_id]/content.js
  client/app/(profiles)/profiles/components/Hero/Profiles/Card.jsx
  client/locales/az.json
  client/locales/en.json
  client/locales/tr.json
  server/src/bot/commands/general/info.js
  server/src/routes/users/[id]/index.js
  server/src/utils/profiles/getBadges.js
Labels: Frontend: Bug, Backend: Bug, Internalization

#54 Fix graphs displayed with zero data
  client/app/(profiles)/profile/[slug]/content.js
Labels: Frontend: Bug, Frontend: UI/UX

#55 Fix localization issues
  client/app/(profiles)/profile/[slug]/components/sections/Graph/Likes.jsx
  client/app/(profiles)/profile/[slug]/components/sections/Graph/Views.jsx
  client/app/(servers)/servers/[id]/components/Tabs/Graph/MonthlyVotes.jsx
Labels: Frontend: Bug, Internalization

#56 Add user status to profile cards
  client/app/(profiles)/profiles/components/Hero/Profiles/Card.jsx
  client/app/(profiles)/profiles/components/Hero/Profiles/index.jsx
  client/lib/request/profiles/fetchPresences.js
  client/locales/az.json
  client/locales/en.json
  client/locales/tr.json
  client/public/profile-badges/black_poweredByLantern.svg
  client/public/profile-badges/white_poweredByLantern.svg
  client/public/status/dnd.svg
  client/public/status/idle.svg
  client/public/status/offline.svg
  client/public/status/online.svg
  client/public/status/streaming.svg
  client/stores/profiles/search/index.js
Labels: Frontend: Feature, Frontend: UI/UX, Internalization
