Repository discordplace/discord.place, pull requests merged in 2024-09, with the labels that each got.

#57 In app reporting
  client/app/(bots)/bots/[id]/components/Tabs/Reviews.jsx
  client/app/(bots)/bots/[id]/components/sections/RightSide/Actions.jsx
  client/app/(bots)/bots/components/Hero/SearchResults/Card/index.jsx
  client/app/(bots)/bots/components/Hero/SearchResults/index.jsx
  client/app/(emojis)/emojis/components/Hero/EmojiCard/Package.jsx
  client/app/(emojis)/emojis/components/Hero/Emojis.jsx
  client/app/(profiles)/profile/[slug]/components/sections/Actions.jsx
  client/app/(profiles)/profile/[slug]/components/sections/Servers.jsx
  client/app/(profiles)/profile/u/[user_id]/content.js
  client/app/(profiles)/profiles/components/Hero/Profiles/Card.jsx
  client/app/(servers)/servers/[id]/components/Tabs/Reviews.jsx
  client/app/(servers)/servers/[id]/components/sections/RightSide/Actions.jsx
  client/app/(servers)/servers/components/Hero/index.jsx
  client/app/(sounds)/sounds/components/Sounds/index.jsx
  client/app/(templates)/templates/components/Hero/SearchResults/Card/index.jsx
  client/app/(templates)/templates/components/Hero/SearchResults/index.jsx
  client/app/components/Providers/ReportButton/index.jsx
  client/app/components/ReportableArea/Previews/Bot.jsx
  client/app/components/ReportableArea/Previews/Emoji.jsx
  client/app/components/ReportableArea/Previews/Profile.jsx
  client/app/components/ReportableArea/Previews/Review.jsx
  client/app/components/ReportableArea/Previews/Server.jsx
  client/app/components/ReportableArea/Previews/Sound.jsx
  client/app/components/ReportableArea/Previews/Template.jsx
  client/app/components/ReportableArea/ReportAreaModal.jsx
  client/app/components/ReportableArea/index.jsx
  client/app/layout-content.js
  client/app/layout.js
  client/config.js
  client/lib/getCompressedName.js
  client/lib/request/createReport.js
  client/locales/az.json
  client/locales/en.json
  client/locales/tr.json
  client/stores/general/index.js
  client/tailwind.config.js
  server/config.yml
  server/src/routes/profiles/[slug]/index.js
  server/src/routes/reports.js
  server/src/routes/users/[id]/index.js
Labels: Frontend: Feature, Frontend: UI/UX, Backend: Bug, Backend: Feature

#62 /blogs page
  client/app/(blogs)/blogs/Hero/Card.jsx
  client/app/(blogs)/blogs/Hero/index.jsx
  client/app/(blogs)/blogs/[id]/components/BackButton.jsx
  client/app/(blogs)/blogs/[id]/components/Header.jsx
  client/app/(blogs)/blogs/[id]/layout.js
  client/app/(blogs)/blogs/[id]/page.js
  client/app/(blogs)/blogs/layout.js
  client/app/(blogs)/blogs/page.js
  client/app/(bots)/bots/components/Hero/index.jsx
  client/app/(emojis)/emojis/components/Hero/index.jsx
  client/app/(profiles)/profiles/components/Hero/index.jsx
  client/app/(servers)/servers/components/Hero/index.jsx
  client/app/(sounds)/sounds/content.js
  client/app/(templates)/templates/components/Hero/index.jsx
  client/app/api/blogs/route.jsx
  client/app/components/CopyButton/index.jsx
  client/app/components/ErrorState/index.jsx
  client/app/components/Footer/index.jsx
  client/app/components/Header/NotCollapsedHeader.jsx
  client/app/components/Header/ServicesDropdown.jsx
  client/app/components/Header/UserSide.jsx
  client/app/components/Logo/WithText.jsx
  client/app/components/Markdown/index.jsx
  client/app/error/page.js
  client/app/not-found.js
  client/app/premium/content.jsx
  client/blogs/hello-from-blogs.md
  client/lib/markdownComponents.jsx
  client/lib/request/fetchBlogs.js
  client/locales/az.json
  client/locales/en.json
  client/locales/tr.json
  client/package.json
  client/pnpm-lock.yaml
  client/public/blogs/hello-from-blogs.jpg
  client/public/sketch/black_line.svg
  client/public/sketch/white_line.svg
  client/stores/general/index.js
  client/tailwind.config.js
Labels: Frontend: Bug, Frontend: UI/UX, Frontend: Performance

#63 Remove fetching guild members bulk
  client/app/(account)/account/components/Content/Tabs/MyServers/NewServer/index.jsx
  client/app/(servers)/servers/[id]/components/Tabs/Graph/VoiceActivity.jsx
  client/app/(servers)/servers/[id]/components/Tabs/index.jsx
  client/app/(servers)/servers/[id]/components/sections/About.jsx
  client/app/(servers)/servers/[id]/manage/components/Other/index.jsx
  client/app/(servers)/servers/[id]/manage/content.js
  client/app/(servers)/servers/components/Hero/index.jsx
  client/app/(servers)/servers/components/ServerCard/index.jsx
  client/config.js
  client/locales/az.json
  client/locales/en.json
  client/locales/tr.json
  server/src/bot/commands/general/info.js
  server/src/bot/events/guildCreate.js
  server/src/bot/events/interactionCreate.js
  server/src/client.js
  server/src/routes/bots/[id]/approve.js
  server/src/routes/bots/[id]/deny.js
  server/src/routes/bots/[id]/reviews/[review_id]/approve.js
  server/src/routes/bots/[id]/reviews/[review_id]/deny.js
  server/src/routes/emojis/[id]/approve.js
  server/src/routes/emojis/[id]/deny.js
  server/src/routes/emojis/[id]/upload-to-guild.js
  server/src/routes/emojis/packages/[id]/upload-to-guild.js
  server/src/routes/payments/webhook.js
  server/src/routes/servers/[id]/index.js
  server/src/routes/servers/[id]/reviews/[review_id]/approve.js
  server/src/routes/servers/[id]/reviews/[review_id]/deny.js
  server/src/routes/servers/search.js
  server/src/routes/sounds/[id]/approve.js
  server/src/routes/sounds/[id]/deny.js
  server/src/routes/sounds/[id]/upload-to-guild.js
  server/src/routes/templates/[id]/approve.js
  server/src/routes/templates/[id]/deny.js
  server/src/routes/users/[id]/index.js
  server/src/schemas/Server/VoiceActivity.js
  server/src/schemas/Server/index.js
  server/src/utils/fetchGuildsMembers.js
  server/src/utils/servers/incrementVote.js
Labels: Frontend: UI/UX, Frontend: Performance, Internalization

#64 Swap to process.hrtime() for high-resolution response time tracking
  server/src/routes/response-time.js
Labels: Backend: Bug

#67 update english locale to follow en-US Int'l writing rules
  client/locales/en.json
Labels: Internalization

#70 Azerbaijani language support for /themes page
  client/locales/az.json
Labels: Internalization
