Repository discordplace/discord.place, pull requests merged in 2024-05, with the labels that each got.

#12 Prevent self reviews
  client/app/(bots)/bots/[id]/components/Tabs/Reviews.jsx
  client/app/(servers)/servers/[id]/components/Tabs/Reviews.jsx
  server/src/routes/bots/[id]/reviews.js
  server/src/routes/servers/[id]/index.js
  server/src/routes/servers/[id]/reviews.js
  server/src/schemas/Bot/index.js
Labels: Frontend: Feature, Backend: Feature

#13 Remove extra comma
  server/jsconfig.json
Labels: Backend: Bug

#14 Add dsc.dog & compability for multiple hostnames for preferred hostnames
  client/app/(profiles)/profile/[slug]/edit/components/Dropdown/PreferredHost.jsx
  client/app/(profiles)/profiles/create/page.js
  client/app/redeem/page.js
  client/config.js
  server/config.yml
  server/src/routes/[slug].js
  server/src/routes/index.js
  server/src/routes/profiles/[slug]/index.js
  server/src/routes/profiles/index.js
  server/src/schemas/Profile/index.js
  server/src/server.js
Labels: Frontend: Feature, Frontend: Performance, Backend: Feature

#19 Vote rewards
  server/src/bot/commands/admin.js
  server/src/bot/commands/server.js
  server/src/schemas/Server/LogChannel.js
  server/src/schemas/Server/Vote/Reward.js
  server/src/utils/servers/incrementVote.js
  server/src/utils/servers/sendLog.js
Labels: Backend: Feature

#25 Add sorting and searching functionality to bots page
  client/app/(bots)/bots/components/Hero/Drawer/Sorting.jsx
  client/app/(bots)/bots/components/Hero/PopularBots/Card/index.jsx
  client/app/(bots)/bots/components/Hero/PopularBots/index.jsx
  client/app/(bots)/bots/components/Hero/SearchInput/index.jsx
  client/app/(bots)/bots/components/Hero/TopCategories/index.jsx
  client/app/(bots)/bots/components/Hero/index.jsx
  client/app/(profiles)/profile/u/[user_id]/content.js
  client/config.js
  client/lib/request/bots/fetchBots.js
  client/stores/bots/search/index.js
  server/src/routes/bots/search.js
  server/src/schemas/Bot/index.js
Labels: Frontend: Feature, Frontend: UI/UX, Backend: Feature

#28 Adding modals provider
  client/app/(bots)/bots/[id]/manage/content.js
  client/app/(dashboard)/components/ReviewsQueue/Table/Approved.jsx
  client/app/(dashboard)/components/ReviewsQueue/Table/WaitingApproval.jsx
  client/app/(dashboard)/components/Timeouts/index.jsx
  client/app/(emojis)/emojis/[id]/content.js
  client/app/(emojis)/emojis/packages/[id]/content.js
  client/app/(profiles)/profile/[slug]/edit/components/DangerZone.jsx
  client/app/(servers)/servers/[id]/manage/content.js
  client/app/components/Providers/Modal/index.jsx
  client/app/layout.js
  client/stores/modals/index.js
  client/styles/radix-animations.css
Labels: Frontend: UI/UX, Frontend: Performance
