Repository discordplace/discord.place, pull requests merged in 2024-06, with the labels that each got.

#21 update: server icon for bot cards
  client/app/(bots)/bots/[id]/components/sections/About.jsx
  client/app/(bots)/bots/components/Hero/Drawer/Sorting.jsx
  client/app/(bots)/bots/components/Hero/PopularBots/Card/index.jsx
  client/app/(bots)/bots/components/Hero/index.jsx
  client/app/(dashboard)/components/Home/index.jsx
Labels: Frontend: UI/UX

#29 fix (frontend): lint rules
  client/app/(bots)/bots/components/Hero/Drawer/Sorting.jsx
  client/app/(bots)/bots/components/Hero/PopularBots/Card/index.jsx
  client/app/(bots)/bots/components/Hero/index.jsx
  client/app/(dashboard)/components/Home/index.jsx
Labels: Frontend: Bug

#32 Betterstack integration
  README.md
  server/.example.env
  server/.gitignore
  server/index.js
  server/package.json
  server/pnpm-lock.yaml
  server/src/bot/commands/emoji.js
  server/src/bot/events/guildCreate.js
  server/src/bot/events/guildMemberAdd.js
  server/src/bot/events/guildUpdate.js
  server/src/bot/events/interactionCreate.js
  server/src/bot/handlers/commands.js
  server/src/bot/handlers/events.js
  server/src/client.js
  server/src/database/connect.js
  server/src/routes/auto-deploy.js
  server/src/routes/blocked-ips/[ip].js
  server/src/routes/bot-denies/[id].js
  server/src/routes/bots/[id]/voters/[user_id]/timeout.js
  server/src/routes/emojis/[id]/deny.js
  server/src/routes/emojis/index.js
  server/src/routes/profiles/[slug]/force-fetch.js
  server/src/routes/servers/[id]/voters/[user_id]/timeout.js
  server/src/schemas/BlockedIp.js
  server/src/schemas/Bot/index.js
  server/src/schemas/Premium.js
  server/src/server.js
  server/src/utils/bots/getApproximateGuildCount.js
  server/src/utils/createMongoBackup.js
  server/src/utils/fetchGuildsMembers.js
  server/src/utils/logger.js
  server/src/utils/middlewares/blockSimultaneousRequests.js
  server/src/utils/middlewares/globalRateLimiter.js
  server/src/utils/servers/incrementVote.js
  server/src/utils/servers/updatePanelMessage.js
Labels: Backend: Feature

#34 New info commands
  server/config.yml
  server/src/bot/commands/features/emoji.js
  server/src/bot/commands/features/server.js
  server/src/bot/commands/features/templates.js
  server/src/bot/commands/features/vote.js
  server/src/bot/commands/general/info.js
  server/src/bot/commands/general/ping.js
  server/src/bot/commands/general/stats.js
  server/src/bot/commands/reminder/index.js
  server/src/bot/commands/reminder/reminders.js
  server/src/bot/events/interactionCreate.js
  server/src/utils/servers/updatePanelMessage.js
Labels: Backend: Feature

#35 Profile card colors
  client/app/(bots)/bots/components/Hero/SearchResults/Card/index.jsx
  client/app/(dashboard)/components/BlockedIps/index.jsx
  client/app/(dashboard)/components/BotDenies/index.jsx
  client/app/(dashboard)/components/BotsQueue/Table/Approved.jsx
  client/app/(dashboard)/components/BotsQueue/Table/WaitingApproval.jsx
  client/app/(dashboard)/components/EmojisQueue/Table/Approved.jsx
  client/app/(dashboard)/components/EmojisQueue/Table/WaitingApproval.jsx
  client/app/(dashboard)/components/ReviewsQueue/Table/Approved.jsx
  client/app/(dashboard)/components/ReviewsQueue/Table/WaitingApproval.jsx
  client/app/(dashboard)/components/TemplatesQueue/Table/Approved.jsx
  client/app/(dashboard)/components/TemplatesQueue/Table/WaitingApproval.jsx
  client/app/(dashboard)/components/Timeouts/index.jsx
  client/app/(profiles)/profile/[slug]/edit/components/Edit.jsx
  client/app/(profiles)/profiles/components/Hero/Profiles/Card.jsx
  client/app/(servers)/servers/components/ServerCard/index.jsx
  client/app/premium/content.jsx
  client/package.json
  client/pnpm-lock.yaml
  server/package.json
  server/pnpm-lock.yaml
  server/src/routes/profiles/[slug]/index.js
  server/src/schemas/Profile/index.js
  server/src/utils/validations/profiles/colors.js
Labels: Frontend: Feature, Frontend: UI/UX, Backend: Feature

#36 New votes store behavior & Stand out feature
  client/app/(bots)/bots/[id]/components/sections/RightSide/Actions.jsx
  client/app/(bots)/bots/[id]/components/sections/RightSide/SupportServer.jsx
  client/app/(bots)/bots/[id]/content.js
  client/app/(bots)/bots/components/Hero/SearchResults/Card/index.jsx
  client/app/(dashboard)/components/Home/Graph/index.jsx
  client/app/(profiles)/profile/[slug]/components/sections/LikesGraph.jsx
  client/app/(servers)/servers/[id]/components/Tabs/Graph/MonthlyVotes.jsx
  client/app/(servers)/servers/[id]/components/Tabs/Graph/VoiceActivity.jsx
  client/app/(servers)/servers/[id]/components/Tabs/index.jsx
  client/app/(servers)/servers/[id]/components/sections/RightSide/Actions.jsx
  client/app/(servers)/servers/[id]/content.js
  client/app/(servers)/servers/components/Hero/index.jsx
  client/app/(servers)/servers/components/ServerCard/index.jsx
  client/lib/request/bots/createStandedOutCheckout.js
  client/lib/request/servers/createStandedOutCheckout.js
  client/public/profile-badges/black_standed_out.svg
  client/public/profile-badges/white_standed_out.svg
  server/config.yml
  server/index.js
  server/package.json
  server/pnpm-lock.yaml
  server/public/favicon.ico
  server/src/bot/commands/general/info.js
  server/src/client.js
  server/src/routes/bots/search.js
  server/src/routes/payments/checkout.js
  server/src/routes/payments/webhook.js
  server/src/routes/servers/[id]/index.js
  server/src/routes/servers/search.js
  server/src/schemas/Bot/index.js
  server/src/schemas/MonthlyVotes.js
  server/src/schemas/Server/MonthlyVotes.js
  server/src/schemas/Server/index.js
  server/src/schemas/StandedOut.js
  server/src/server.js
  server/src/utils/bots/incrementVote.js
  server/src/utils/payments/createStandedOutCheckout.js
  server/src/utils/servers/incrementVote.js
  server/src/utils/servers/updatePanelMessage.js
  server/src/utils/updateMonthlyVotes.js
  server/src/utils/useRateLimiter.js
  server/startup/registerCommands.js
  server/startup/unregisterCommands.js
Labels: Frontend: Feature, Frontend: UI/UX, Backend: Feature
