Repository discordplace/discord.place, pull requests merged in 2025-01, with the labels that each got.

#153 feat: remove snowfall effect
  client/app/layout-content.js
  client/package.json
  client/pnpm-lock.yaml
Labels: Frontend: Feature, Frontend: UI/UX, Frontend: Performance

#154 fix: correct user ID for most voted user in database, add is_most_vot…
  server/src/schemas/MonthlyVotes.js
  server/src/utils/updateMonthlyVotes.js
Labels: Backend: Bug, Backend: Feature

#155 feat: add most voted badge to bot/server cards based on monthly votes
  client/app/(bots)/bots/components/Hero/SearchResults/Card/index.jsx
  client/app/(servers)/servers/components/Hero/index.jsx
  client/app/(servers)/servers/components/ServerCard/index.jsx
  client/locales/az.json
  client/locales/en.json
  client/locales/tr.json
  server/src/routes/bots/search.js
  server/src/routes/servers/search.js
Labels: Frontend: Feature

#156 fix(docs): add server_count field to mock data in getting-started page
  docs/app/getting-started/page.mdx
Labels: Frontend: Bug

#158 feat(profile/socials): update styles
  client/app/(profiles)/profile/[slug]/components/sections/Social.jsx
  client/app/(profiles)/profile/[slug]/edit/components/Socials.jsx
  client/app/(profiles)/profile/[slug]/edit/components/VerifiedBadge.jsx
  client/lib/utils/profiles/colors.js
  client/lib/utils/profiles/getIcon.js
  client/public/profile-social-icons/black_github.svg
  client/public/profile-social-icons/black_tiktok.svg
  client/public/profile-social-icons/black_x.svg
  client/public/profile-social-icons/facebook.svg
  client/public/profile-social-icons/instagram.svg
  client/public/profile-social-icons/steam.svg
  client/public/profile-social-icons/telegram.svg
  client/public/profile-social-icons/twitch.svg
  client/public/profile-social-icons/twitter.svg
  client/public/profile-social-icons/white_github.svg
  client/public/profile-social-icons/white_tiktok.svg
  client/public/profile-social-icons/white_x.svg
  client/public/profile-social-icons/youtube.svg
Labels: Frontend: UI/UX
